# Generated by Django 4.2 on 2023-05-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('access_token', models.CharField(max_length=200)),
                ('token_type', models.CharField(max_length=20)),
                ('expires_in', models.DateTimeField()),
                ('refresh_token', models.CharField(max_length=200)),
                ('user_name', models.CharField(default='Null', max_length=30)),
                ('user_pfp_url', models.URLField(default='Null')),
                ('user_name_id', models.CharField(default='Null', max_length=40)),
            ],
        ),
    ]
