# Generated by Django 4.2.1 on 2023-05-05 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_alter_spotifytoken_expires_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotifytoken',
            name='token_type',
        ),
        migrations.AlterField(
            model_name='spotifytoken',
            name='access_token',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='spotifytoken',
            name='refresh_token',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='spotifytoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spotify_token', to=settings.AUTH_USER_MODEL),
        ),
    ]
